version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4478:4478"
    environment:
      PRISMA_CONFIG: |
        port: 4478
        #uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        databases:
          default:
            connector: mongo
            uri: 'mongodb+srv://rapidBryan:rapidJaguar123@rapidjaguar-xftyz.gcp.mongodb.net/test?retryWrites=true&w=majority'
  mongo:
    image: mongo:3.6
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Compass
    # ports:
    # - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rapidBryan
      MONGO_INITDB_ROOT_PASSWORD: rapidJaguar123
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: